services:
  quartz:
    build: .
    ports:
      - "8080:8080"
    # overrides for local development
    volumes:
      - ./content:/app/content
      - ./data:/app/data
      - ./quartz.config.ts:/app/quartz.config.ts
      - ./quartz.layout.ts:/app/quartz.layout.ts
    environment:
      - NODE_ENV=development
    command: npx quartz build --serve
