
services:
  hugo:
    image: klakegg/hugo:0.111.3-ext-debian-onbuild
    command: server --bind=0.0.0.0 --baseURL=http://localhost:1313 --appendPort=false --noHTTPCache
    ports:
      - "1313:1313"
    volumes:
      - ./:/src
    environment:
      - HUGO_ENV=development
    user: "${UID:-1000}:${GID:-1000}"
