# You may need to change this line for your real project.
baseURL = 'https://pq3.ru/'

# A "copyright"-line to be added to RSS/Atom files and the footer.
copyright = '© 2015-2025 Oleg Y. Danilkiff'

# Keep title short to prevent overflow.
# There’s no official guidance on this, but 40 characters for
# mobile and 60 for desktop is roughly the sweet spot.
#
# NB: Final title of shareable pages will be this plus the
#     title of the page. E.g. "Posts | Ed."
title = "[Mind Cloud]"

[module]
  [module.hugoVersion]
    extended = true
  [[module.imports]]
    # Use full path to theme's repository. This is replaced in go.mod for
    # exampleSite to point to the directory above.
    path = 'github.com/adityatelange/hugo-PaperMod'

enableRobotsTXT = true

# When using ref or relref to resolve page links and a link cannot
# resolve, it will be logged with this log level.
refLinksErrorLevel = 'WARNING'


# For more see https://gohugo.io/content-management/menus/
[menus]
  [[menus.main]]        # sections in the website sidebar
    identifier = 'home' # menu item id
    name = 'Home'       # menu item display title
    pageRef = '/'       # path to the page
    weight = 1          # order of the menu item
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 2
  [[menus.main]]
    identifier = 'credits'
    name = 'Credits'
    pageRef = '/credits'
    weight = 3
  [[menus.main]]
    identifier = 'documentation'
    name = 'Documentation'
    pageRef = '/documentation'
    weight = 4
  [[menus.main]]
    identifier = 'search'
    name = 'Search'
    pageRef = '/search'
    weight = 5
  [[menus.main]]
    identifier = 'contact'
    name = 'Contact'
    pageRef = '/contact'
    weight = 6
  [[menus.main]]
    identifier = 'github'
    name = 'GitHub Project'
    url = 'https://github.com/sergeyklay/gohugo-theme-ed/'
    weight = 20
    params = {external = true}

  [[menus.feeds]]
    identifier = 'rss'
    name = 'RSS 2.0'
    url = '/rss.xml'
    weight = 1
  [[menus.feeds]]
    identifier = 'atom'
    name = 'Atom'
    url = '/atom.xml'
    weight = 2
  [[menus.feeds]]
    identifier = 'json'
    name = 'Json Feed'
    url = '/feed.json'
    weight = 3

[pagination]
  pagerSize = 10

# We have just the default tags taxonomy, and remove the categories
# taxonomy for site as not used.
[taxonomies]
  tag = 'tags'
  category = 'categories'
