# You may need to change this line for your real project.
baseURL = '/'

# A "copyright"-line to be added to RSS/Atom files and the footer.
copyright = '© 2015-2025 Oleg Y. Danilkiff'

# Keep title short to prevent overflow.
# There’s no official guidance on this, but 40 characters for
# mobile and 60 for desktop is roughly the sweet spot.
#
# NB: Final title of shareable pages will be this plus the
#     title of the page. E.g. "Posts | Ed."
title = "[Mind Cloud]"

enableRobotsTXT = true
enableGitInfo = true

# https://github.com/ikatyang/emoji-cheat-sheet
# shortcode `:heart:` = ❤️
enableEmoji = true

# When using ref or relref to resolve page links and a link cannot
# resolve, it will be logged with this log level.
refLinksErrorLevel = 'WARNING'

googleAnalytics = 'GTM-MTL65HW3'

[params]
  # Site description. Used in meta description
  description = 'Advanced systems thinking for CTOs and engineering leaders: actionable frameworks for architecture, reliability, team capabilities, and organizational growth.'

  # SEO keywords. Used in 'meta name="keywords"' tag.
  # May be overridden by .Keywords or .Tags in front matter.
  keywords = ['systems thinking', 'engineering leadership', 'software architecture', 'reliability engineering', 'organizational learning', 'team capabilities', 'collective intelligence', 'devops culture', 'technical debt', 'reasoning frameworks', 'resilience', 'IT strategy', 'capability drift', 'postmortem analysis', 'platform engineering', 'incident management', 'knowledge transfer', 'engineering management', 'technical excellence', 'engineering culture']

  # Used in site header
  tagline = 'Resilience by design. Reasoning by default.'

  # Custom footer text on left sidebar. Use HTMl if needed.
  # "&copy;" and "{year}" will be replaced by © and the current year.
  footer = 'Built with <a href="https://github.com/sergeyklay/gohugo-theme-ed" target="_blank" rel="noopener noreferrer">Ed</a>. Distributed under an MIT license.'

  # Posts date format, for example: 2006-01-02
  dateFormat = '2006-01-02'
  dateFormatToc = '2006-01-02'

  # Show "Read more" button in list if true
  readmore = true

  # RSS/Atom feed size
  feedSize = 25
  recentPostsSize = 9999


  # Site icons, relative to ./static
  [params.assets]
    # favicon.ico for legacy browsers
    favicon = 'favicon.ico'

    # A single SVG icon with a light/dark version for modern browsers
    svgicon = 'favicon.svg'

    # 180×180 PNG image for Apple devices
    apple_touch_icon = ''

    # Logo image, relative to ./assets
    logo = '/img/open-graph-logo.png'
    disable_fingerprinting = false

  [params.seo]
    # Will be used in schema.org/Organization.
    # The site.Title  will be used if empty.
    publisher = 'Oleg Y. Danilkiff'

  # Configure search engine
  [params.search]
    # Maximum length (in words) of each text blurb. You can change this
    # value if you find that 100 is too short or too long for your taste.
    maxSummaryLength = 100
    # Lunr has full support for the indexing and searching of documents
    # in English. If your documents are in another language, uncomment
    # required languages below.
    #
    # For more see: https://lunrjs.com/guides/language_support.html
    languages = ['en', 'es']

# For more see https://gohugo.io/content-management/menus/
[menus]
  [[menus.main]]        # sections in the website sidebar
    identifier = 'home' # menu item id
    name = 'Home'       # menu item display title
    pageRef = '/'       # path to the page
    weight = 1          # order of the menu item
  
  [[menus.main]]
    identifier = 'search'
    name = 'Search'
    pageRef = '/search'
    weight = 5

[pagination]
  pagerSize = 10

# We have just the default tags taxonomy, and remove the categories
# taxonomy for site as not used.
[taxonomies]
  tag = 'tags'
  category = 'categories'

# Sitemap config
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

# For more see https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    # false due to generated Syntax Highlighter CSS
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        # Enable custom attribute support for blocks
        block = true

# If enableGitInfo is true, it will override any lastmod dates in our
# front matter. We should at least allow ourselves to manually override
# this value in the front matter.
[frontmatter]
  lastmod = ['lastmod', ':git', 'modified', 'date', 'publishdate', 'pubdate', 'published']

[module]
  [module.hugoVersion]
    extended = true
    min = '0.121.0'
  [[module.imports]]
    # Use full path to theme's repository. This is replaced in go.mod for
    # exampleSite to point to the directory above.
    path = 'github.com/sergeyklay/gohugo-theme-ed'

[minify]
  # Do not minify XML files to avoid CDATA escape issues
  disableXML = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true

[build]
  # This is used to dump and array of the class attributes, id attributes,
  # and tags of every HTML element within your published site.
  # This datd can be used as a source when removing unused CSS from site.
  # For more see: https://gohugo.io/hugo-pipes/postprocess/#css-purging-with-postcss
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true
