copyright = '© 2015-2025 Oleg Y. Danilkiff'
title = "[Mind Cloud]"

enableRobotsTXT = true
enableGitInfo = true

# https://github.com/ikatyang/emoji-cheat-sheet
# shortcode `:heart:` = ❤️
enableEmoji = true

[params]
  # papermod only
  ShowReadingTime = true
  
  # Site description. Used in meta description
  description = 'Advanced systems thinking for CTOs and engineering leaders: actionable frameworks for architecture, reliability, team capabilities, and organizational growth.'

  # SEO keywords. Used in 'meta name="keywords"' tag.
  # May be overridden by .Keywords or .Tags in front matter.
  keywords = ['systems thinking', 'engineering leadership', 'software architecture', 'reliability engineering', 'organizational learning', 'team capabilities', 'collective intelligence', 'devops culture', 'technical debt', 'reasoning frameworks', 'resilience', 'IT strategy', 'capability drift', 'postmortem analysis', 'platform engineering', 'incident management', 'knowledge transfer', 'engineering management', 'technical excellence', 'engineering culture']

  # Used in site header
  tagline = 'Resilience by design. Reasoning by default.'

  # Posts date format, for example: 2006-01-02
  dateFormat = '2006-01-02'
  dateFormatToc = '2006-01-02'


  # Site icons, relative to ./static
  [params.assets]
    # favicon.ico for legacy browsers
    favicon = 'favicon.ico'

    # A single SVG icon with a light/dark version for modern browsers
    svgicon = 'favicon.svg'

    # 180×180 PNG image for Apple devices
    apple_touch_icon = ''

    # Logo image, relative to ./assets
    logo = '/img/open-graph-logo.png'
    disable_fingerprinting = false

    # [params.homeInfoParams]
    #   Title = ''

    [params.profileMode]
      enabled = true
      imageUrl = '/img/open-graph-logo.png'
      title = '...'
      subtitle = 'Resilience by design. Reasoning by default.'
    
    [[params.profileMode.buttons]]
      name = 'About'
      url = '/about/'
    
    [[params.profileMode.buttons]]
      name = 'View posts'
      url = '/posts/'

    [[params.profileMode.buttons]]
      name = 'Why this blog exists?'
      url = '/why/'

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/danilkiff"
    
    [[params.socialIcons]]
      name = "orcid"
      url = "https://orcid.org/0009-0002-8031-2575"

    [[params.socialIcons]]
      name = "telegram"
      url = "https://t.me/danilkiff"
    

# For more see https://gohugo.io/content-management/menus/
[menus]
  [[menus.main]]            # sections in the website sidebar
    identifier = 'arhive'  # menu item id
    name = 'Archive'       # menu item display title
    pageRef = '/archive'   # path to the page
    weight = 1              # order of the menu item
  
  [[menus.main]]            # sections in the website sidebar
    identifier = 'tags'  # menu item id
    name = 'Tags'       # menu item display title
    pageRef = '/tags'   # path to the page
    weight = 2              # order of the menu item
  
  [[menus.main]]            # sections in the website sidebar
    identifier = 'books'  # menu item id
    name = 'Books'       # menu item display title
    pageRef = '/books'   # path to the page
    weight = 3              # order of the menu item

  

# We have just the default tags taxonomy, and remove the categories
# taxonomy for site as not used.
[taxonomies]
  tag = 'tags'
  category = 'categories'

# Sitemap config
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

# For more see https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    # false due to generated Syntax Highlighter CSS
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        # Enable custom attribute support for blocks
        block = true

# If enableGitInfo is true, it will override any lastmod dates in our
# front matter. We should at least allow ourselves to manually override
# this value in the front matter.
[frontmatter]
  lastmod = ['lastmod', ':git', 'modified', 'date', 'publishDate', 'pubdate']

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

