name: Build and Deploy Quartz 4

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npx quartz build

      - name: Archive build output
        run: tar czf out.tar.gz -C public .

      - name: Copy build to server (atomic release)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "out.tar.gz"
          target: "/var/www/pikachuoverflow.ru/releases/${{ github.sha }}"

      - name: Atomic switch & cleanup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/pq3.ru/releases/${{ github.sha }}
            tar xzf out.tar.gz -C .
            rm out.tar.gz
            ln -sfn /var/www/pq3.ru/releases/${{ github.sha }} /var/www/pq3.ru/html
            cd /var/www/pq3.ru/releases
            ls -1dt */ | tail -n +3 | xargs -r rm -rf
