name: Build and Deploy Quartz 4

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

        # Exiting Quartz due to a fatal error: EBUSY: resource busy or locked, rmdir 'public'
        # if `docker run --rm -v ${{ github.workspace }}/public:/app/public quartz4-build npx quartz build`
      - name: Build site in Docker
        run: |
            docker build -t quartz4-build .
            docker run --name artifacts quartz4-build npx quartz build
            docker cp artifacts:/app/public ./public
            docker rm artifacts


      - name: Archive build output
        run: tar czf out.tar.gz -C public .

      - name: Copy build to server (atomic release)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "out.tar.gz"
          target: "/var/www/pq3.ru/releases/${{ github.sha }}"

      - name: Atomic switch & cleanup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /var/www/pq3.ru/releases/${{ github.sha }}
            tar xzf out.tar.gz -C .
            rm out.tar.gz
            ln -sfn /var/www/pq3.ru/releases/${{ github.sha }} /var/www/pq3.ru/html
            cd /var/www/pq3.ru/releases
            ls -1dt */ | tail -n +3 | xargs -r rm -rf
